name: Daily Scraping Anime Data

on:
  schedule:
    - cron: '0 0 * * *'  # everyday at 7 AM GMT+7


jobs:
  schedule-scrape:
    runs-on: macos-latest
    env:
      ONGOING_COLLECTION: ${{ secrets.ONGOING_COLLECTION }}
      TOPAIRING_COLLECTION: ${{ secrets.TOPAIRING_COLLECTION }}
      TOPUPCOMING_COLLECTION: ${{ secrets.TOPUPCOMING_COLLECTION }}
      TOPTV_COLLECTION: ${{ secrets.TOPTV_COLLECTION }}
      TOPMOVIE_COLLECTION: ${{ secrets.TOPMOVIE_COLLECTION }}
      ANIME_DATABASE: ${{ secrets.ANIME_DATABASE }}
      ATLAS_URL: ${{ secrets.ATLAS_URL }}

    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'        
      - name: Install stringr package
        run: Rscript -e 'install.packages("stringr", dependencies = TRUE)'
      - name: Install tidyr package
        run: Rscript -e 'install.packages("tidyr", dependencies = TRUE)' 
      - name: Install plyr package
        run: Rscript -e 'install.packages("plyr", dependencies = TRUE)' 
      - name: Scrape data 
        run: Rscript daily_scrape.R
